In [ ]:
import pandas as pd
import os
import re
import unicodedata

In [ ]:
CARPETA_SALIDA = "salida"

if not os.path.exists(CARPETA_SALIDA):
    os.makedirs(CARPETA_SALIDA)

In [ ]:
df = pd.read_csv("netflix.csv", sep=';')

In [ ]:
# Columnas que vamos a limpiar
columnas = ["title", "director", "cast", "country"]

# Función para quitar tildes, Ñ y caracteres especiales
def limpiar_texto(texto):
    if pd.isna(texto):
        return texto

    # quitar tildes y convertir Ñ -> N
    texto = unicodedata.normalize("NFKD", str(texto))
    texto = texto.encode("ascii", "ignore").decode("utf-8")

    # dejar solo letras, numeros, espacios y algunos signos
    texto = re.sub(r"[^a-zA-Z0-9\s,.-]", "", texto)

    return texto


# Aplicar solo a esas columnas
for columna in columnas:
    df[columna] = df[columna].apply(limpiar_texto)


# Mostrar resultado
print(df[columnas].head(10))

                             title                       director  \
0             Dick Johnson Is Dead                Kirsten Johnson
1                     Blood  Water                            NaN
2                        Ganglands                Julien Leclercq
3            Jailbirds New Orleans                            NaN
4                     Kota Factory                            NaN
5                    Midnight Mass                  Mike Flanagan
6  My Little Pony A New Generation  Robert Cullen, Jose Luis Ucha
7                          Sankofa                   Haile Gerima
8    The Great British Baking Show                Andy Devonshire
9                     The Starling                 Theodore Melfi

                                                cast  \
0                                                NaN
1  Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...
2  Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...
3                                                NaN
4  Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...
5  Kate Siegel, Zach Gilford, Hamish Linklater, H...
6  Vanessa Hudgens, Kimiko Glenn, James Marsden, ...
7  Kofi Ghanaba, Oyafunmike Ogunlano, Alexandra D...
8  Mel Giedroyc, Sue Perkins, Mary Berry, Paul Ho...
9  Melissa McCarthy, Chris ODowd, Kevin Kline, Ti...

                                             country
0                                      United States
1                                       South Africa
2                                                NaN
3                                                NaN
4                                              India
5                                                NaN
6                                                NaN
7  United States, Ghana, Burkina Faso, United Kin...
8                                     United Kingdom
9                                      United States

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8808 entries, 0 to 8807
Data columns (total 11 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   show_id       8808 non-null   object
 1   type          8807 non-null   object
 2   title         8808 non-null   object
 3   director      6173 non-null   object
 4   cast          7981 non-null   object
 5   country       7976 non-null   object
 6   date_added    8797 non-null   object
 7   release_year  8807 non-null   float64
 8   rating        8800 non-null   object
 9   duration      8807 non-null   object
 10  listed_in     8807 non-null   object
dtypes: float64(1), object(10)
memory usage: 757.1+ KB

In [ ]:
df.head()

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,"September 25, 2021",2020.0,PG-13,90 min,Documentaries
1,s2,TV Show,Blood Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021.0,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries"
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,"September 24, 2021",2021.0,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act..."
3,s4,TV Show,Jailbirds New Orleans,NaN,NaN,NaN,"September 24, 2021",2021.0,TV-MA,1 Season,"Docuseries, Reality TV"
4,s5,TV Show,Kota Factory,NaN,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,"September 24, 2021",2021.0,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ..."

In [ ]:
df.tail()

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in
8803,s8803,Movie,Zodiac,David Fincher,"Mark Ruffalo, Jake Gyllenhaal, Robert Downey J...",United States,"November 20, 2019",2007.0,R,158 min,"Cult Movies, Dramas, Thrillers"
8804,s8804,TV Show,Zombie Dumb,NaN,NaN,NaN,"July 1, 2019",2018.0,TV-Y7,2 Seasons,"Kids' TV, Korean TV Shows, TV Comedies"
8805,s8805,Movie,Zombieland,Ruben Fleischer,"Jesse Eisenberg, Woody Harrelson, Emma Stone, ...",United States,"November 1, 2019",2009.0,R,88 min,"Comedies, Horror Movies"
8806,s8806,Movie,Zoom,Peter Hewitt,"Tim Allen, Courteney Cox, Chevy Chase, Kate Ma...",United States,"January 11, 2020",2006.0,PG,88 min,"Children & Family Movies, Comedies"
8807,s8807,Movie,Zubaan,Mozez Singh,"Vicky Kaushal, Sarah-Jane Dias, Raaghav Chanan...",India,"March 2, 2019",2015.0,TV-14,111 min,"Dramas, International Movies, Music & Musicals"

Elimino Espacios

In [ ]:
for columna in df.select_dtypes(include="object").columns:
    df[columna] = df[columna].str.strip()

Elimino registros duplicados

In [ ]:
df = df.drop_duplicates()

Cambio valores nulos

In [ ]:
df["director"] = df["director"].fillna("Sin Director")
df["cast"] = df["cast"].fillna("Sin Actor")
df["country"] = df["country"].fillna("Sin País")
df["rating"] = df["rating"].fillna("Sin Clasificación")
df["date_added"] = df["date_added"].fillna("")
df["duration"] = df["duration"].fillna("")
df["listed_in"] = df["listed_in"].fillna("Sin Género")

Convertir fecha

In [ ]:
df["date_added"] = pd.to_datetime(df["date_added"],errors="coerce")

print(df.info())
print(df.head())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8808 entries, 0 to 8807
Data columns (total 11 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   show_id       8808 non-null   object
 1   type          8807 non-null   object
 2   title         8808 non-null   object
 3   director      8808 non-null   object
 4   cast          8808 non-null   object
 5   country       8808 non-null   object
 6   date_added    8797 non-null   datetime64[ns]
 7   release_year  8807 non-null   float64
 8   rating        8808 non-null   object
 9   duration      8808 non-null   object
 10  listed_in     8808 non-null   object
dtypes: datetime64[ns](1), float64(1), object(9)
memory usage: 757.1+ KB
None
  show_id     type                  title         director  \
0      s1    Movie   Dick Johnson Is Dead  Kirsten Johnson
1      s2  TV Show           Blood  Water     Sin Director
2      s3  TV Show              Ganglands  Julien Leclercq
3      s4  TV Show  Jailbirds New Orleans     Sin Director
4      s5  TV Show           Kota Factory     Sin Director

                                                cast        country  \
0                                          Sin Actor  United States
1  Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...   South Africa
2  Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...       Sin País
3                                          Sin Actor       Sin País
4  Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...          India

  date_added  release_year rating   duration  \
0 2021-09-25        2020.0  PG-13     90 min
1 2021-09-24        2021.0  TV-MA  2 Seasons
2 2021-09-24        2021.0  TV-MA   1 Season
3 2021-09-24        2021.0  TV-MA   1 Season
4 2021-09-24        2021.0  TV-MA  2 Seasons

                                           listed_in
0                                      Documentaries
1    International TV Shows, TV Dramas, TV Mysteries
2  Crime TV Shows, International TV Shows, TV Act...
3                             Docuseries, Reality TV
4  International TV Shows, Romantic TV Shows, TV ...

Separamos la duración

In [ ]:
def separar_duracion(valor):

    if pd.isna(valor):
        return 0, ""

    valor = str(valor)
    numero = re.findall(r"\d+", valor)
    unidad = re.findall(r"[A-Za-z]+", valor)

    if numero:
        numero = int(numero[0])
    else:
        numero = 0

    if unidad:
        unidad = " ".join(unidad)
    else:
        unidad = ""

    return numero, unidad


df[["duration_value", "duration_unit"]] = df["duration"].apply(
    lambda x: pd.Series(separar_duracion(x)))

In [ ]:
print(df.info())
print(df.head())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8808 entries, 0 to 8807
Data columns (total 13 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   show_id         8808 non-null   object
 1   type            8807 non-null   object
 2   title           8808 non-null   object
 3   director        8808 non-null   object
 4   cast            8808 non-null   object
 5   country         8808 non-null   object
 6   date_added      8797 non-null   datetime64[ns]
 7   release_year    8807 non-null   float64
 8   rating          8808 non-null   object
 9   duration        8808 non-null   object
 10  listed_in       8808 non-null   object
 11  duration_value  8808 non-null   int64
 12  duration_unit   8808 non-null   object
dtypes: datetime64[ns](1), float64(1), int64(1), object(10)
memory usage: 894.7+ KB
None
  show_id     type                  title         director  \
0      s1    Movie   Dick Johnson Is Dead  Kirsten Johnson
1      s2  TV Show           Blood  Water     Sin Director
2      s3  TV Show              Ganglands  Julien Leclercq
3      s4  TV Show  Jailbirds New Orleans     Sin Director
4      s5  TV Show           Kota Factory     Sin Director

                                                cast        country  \
0                                          Sin Actor  United States
1  Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...   South Africa
2  Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...       Sin País
3                                          Sin Actor       Sin País
4  Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...          India

  date_added  release_year rating   duration  \
0 2021-09-25        2020.0  PG-13     90 min
1 2021-09-24        2021.0  TV-MA  2 Seasons
2 2021-09-24        2021.0  TV-MA   1 Season
3 2021-09-24        2021.0  TV-MA   1 Season
4 2021-09-24        2021.0  TV-MA  2 Seasons

                                           listed_in  duration_value  \
0                                      Documentaries              90
1    International TV Shows, TV Dramas, TV Mysteries               2
2  Crime TV Shows, International TV Shows, TV Act...               1
3                             Docuseries, Reality TV               1
4  International TV Shows, Romantic TV Shows, TV ...               2

  duration_unit
0           min
1       Seasons
2        Season
3        Season
4       Seasons

Un Backup "limpio"

In [ ]:
df.to_csv(
    os.path.join(CARPETA_SALIDA, "netflix_limpio.csv"),
    index=False,
    encoding="utf-8-sig"
)

CREO TABLA TIPO

In [ ]:
tipo = df[["type"]].drop_duplicates()

# Ordenamos
tipo = tipo.sort_values("type").reset_index(drop=True)

tipo.insert(0, "tipo_id", range(1, len(tipo)+1))

print(tipo)

# Guardo CSV
tipo.to_csv(
    os.path.join(CARPETA_SALIDA, "tipo.csv"),index=False, encoding="utf-8-sig")

   tipo_id     type
0        1    Movie
1        2  TV Show
2        3      NaN

CREO TABLA CLASIFICACION

In [ ]:
clasificacion = df[["rating"]].drop_duplicates()

clasificacion = clasificacion.sort_values("rating").reset_index(drop=True)

clasificacion.insert(0,"cla_id",range(1, len(clasificacion)+1))

print(clasificacion)

# Guardo CSV
clasificacion.to_csv(
    os.path.join(CARPETA_SALIDA, "clasificacion.csv"),index=False,
    encoding="utf-8-sig"
)

    cla_id             rating
0        1                  G
1        2              NC-17
2        3                 NR
3        4                 PG
4        5              PG-13
5        6                  R
6        7  Sin Clasificación
7        8              TV-14
8        9               TV-G
9       10              TV-MA
10      11              TV-PG
11      12               TV-Y
12      13              TV-Y7
13      14           TV-Y7-FV
14      15                 UR

CREO TABLA PAIS

In [ ]:
lista_paises = []

for fila in df["country"]:
    if pd.isna(fila):
        continue

    for pais in str(fila).split(","):
        pais = pais.strip()

        if pais != "":
            lista_paises.append(pais)

pais = pd.DataFrame(sorted(set(lista_paises)), columns=["country"])
#Elimino repetidos
pais.insert(0, "pais_id",range(1, len(pais)+1))

print(pais.head())
print(pais.tail())

#GUARDO CSV
pais.to_csv(os.path.join(CARPETA_SALIDA, "pais.csv"), index=False,
    encoding="utf-8-sig")

   pais_id      country
0        1  Afghanistan
1        2      Albania
2        3      Algeria
3        4       Angola
4        5    Argentina
     pais_id       country
118      119  Vatican City
119      120     Venezuela
120      121       Vietnam
121      122  West Germany
122      123      Zimbabwe

CREO TABLA ACTORES

In [ ]:
lista_actores = []

for fila in df["cast"]:
    if pd.isna(fila):
        continue

    for actor in str(fila).split(","):
        actor = actor.strip()

        if actor != "":
            lista_actores.append(actor)

actor = pd.DataFrame(sorted(set(lista_actores)), columns=["nom_cast"])
#Elimino repetidos
actor.insert(0, "actor_id",range(1, len(actor)+1))

print(actor.head())
print(actor.tail())

#GUARDO CSV
pais.to_csv(os.path.join(CARPETA_SALIDA, "actor.csv"), index=False,
    encoding="utf-8-sig")

   actor_id  nom_cast
0         1  2 Chainz
1         2      2Mex
2         3   4Minute
3         4   50 Cent
4         5      9m88
       actor_id               nom_cast
36371     36372  rostur Leo Gunnarsson
36372     36373  ukasz Lotek Lodkowski
36373     36374    vivienne Rutherford
36374     36375       ystein Martinsen
36375     36376            ystein Rger

CREO TABLA DIRECTORES

In [ ]:
lista_directores = []

for fila in df["director"]:
    if pd.isna(fila):
        continue

    for director in str(fila).split(","):
        director = director.strip()

        if director != "":
            lista_directores.append(director)

director = pd.DataFrame(sorted(set(lista_directores)), columns=["director"])
#Elimino repetidos
director.insert(0, "direc_id",range(1, len(director)+1))

print(director.head())
print(director.tail())

#GUARDO CSV
director.to_csv(os.path.join(CARPETA_SALIDA, "director.csv"), index=False,
    encoding="utf-8-sig")

   direc_id         director
0         1      A. L. Vijay
1         2     A. Raajdheep
2         3        A. Salaam
3         4  A.R. Murugadoss
4         5  Aadish Keluskar
      direc_id          director
4987      4988  Zoe Lister-Jones
4988      4989       Zoya Akhtar
4989      4990       Zsolt Palfi
4990      4991       Zuko Nodada
4991      4992         Zune Kwok

CREO TABLA GENERO

In [ ]:
lista_generos = []

for fila in df["listed_in"]:
    if pd.isna(fila):
        continue

    for genero in str(fila).split(","):
        genero = genero.strip()

        if genero != "":
            lista_generos.append(genero)

genero = pd.DataFrame(sorted(set(lista_generos)), columns=["listed_in"])
#Elimino repetidos
genero.insert(0, "gen_id",range(1, len(genero)+1))

print(genero.head())
print(genero.tail())

#GUARDO CSV
genero.to_csv(os.path.join(CARPETA_SALIDA, "genero.csv"), index=False,
    encoding="utf-8-sig")

   gen_id                 listed_in
0       1        Action & Adventure
1       2            Anime Features
2       3              Anime Series
3       4          British TV Shows
4       5  Children & Family Movies
    gen_id            listed_in
38      39  TV Sci-Fi & Fantasy
39      40             TV Shows
40      41         TV Thrillers
41      42        Teen TV Shows
42      43            Thrillers

CREO TABLA FECHA

In [ ]:
fecha = df[["date_added"]].drop_duplicates().copy()

# elimino fechas vacías
fecha = fecha.dropna()

fecha["year"] = fecha["date_added"].dt.year
fecha["month"] = fecha["date_added"].dt.month
fecha["day"] = fecha["date_added"].dt.day

fecha["nom_month"] = fecha["date_added"].dt.month_name()
fecha["nom_day"] = fecha["date_added"].dt.day_name()
fecha = fecha.reset_index(drop=True)

fecha.insert(0,"fe_id",range(1,len(fecha)+1))

print(fecha.head())
print(fecha.tail())

fecha.to_csv(
    os.path.join(CARPETA_SALIDA,"fecha.csv"),index=False,
    encoding="utf-8-sig"
)

   fe_id date_added  year  month  day  nom_month    nom_day
0      1 2021-09-25  2021      9   25  September   Saturday
1      2 2021-09-24  2021      9   24  September     Friday
2      3 2021-09-23  2021      9   23  September   Thursday
3      4 2021-09-22  2021      9   22  September  Wednesday
4      5 2021-09-21  2021      9   21  September    Tuesday
      fe_id date_added  year  month  day nom_month    nom_day
1709   1710 2017-11-04  2017     11    4  November   Saturday
1710   1711 2015-08-05  2015      8    5    August  Wednesday
1711   1712 2018-12-06  2018     12    6  December   Thursday
1712   1713 2016-03-09  2016      3    9     March  Wednesday
1713   1714 2020-01-11  2020      1   11   January   Saturday

In [218]:
#Copiamos el dataframe
pelicula = df.copy()

In [219]:
#Relacionamos
pelicula = pelicula.merge(tipo,on="type",how="left")

In [220]:
#Relacionamos CLASIFICACION
pelicula = pelicula.merge(clasificacion,on="rating",how="left")

In [221]:
#Relacionamos FECHA
pelicula = pelicula.merge(fecha[["date_added", "fe_id"]],on="date_added",
    how="left")

In [222]:
print(pelicula.head())

  show_id     type                  title         director  \
0      s1    Movie   Dick Johnson Is Dead  Kirsten Johnson
1      s2  TV Show           Blood  Water     Sin Director
2      s3  TV Show              Ganglands  Julien Leclercq
3      s4  TV Show  Jailbirds New Orleans     Sin Director
4      s5  TV Show           Kota Factory     Sin Director

                                                cast        country  \
0                                          Sin Actor  United States
1  Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...   South Africa
2  Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...       Sin País
3                                          Sin Actor       Sin País
4  Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...          India

  date_added  release_year rating   duration  \
0 2021-09-25        2020.0  PG-13     90 min
1 2021-09-24        2021.0  TV-MA  2 Seasons
2 2021-09-24        2021.0  TV-MA   1 Season
3 2021-09-24        2021.0  TV-MA   1 Season
4 2021-09-24        2021.0  TV-MA  2 Seasons

                                           listed_in  duration_value  \
0                                      Documentaries              90
1    International TV Shows, TV Dramas, TV Mysteries               2
2  Crime TV Shows, International TV Shows, TV Act...               1
3                             Docuseries, Reality TV               1
4  International TV Shows, Romantic TV Shows, TV ...               2

  duration_unit  tipo_id  cla_id  fe_id
0           min        1       5    1.0
1       Seasons        2      10    2.0
2        Season        2      10    2.0
3        Season        2      10    2.0
4       Seasons        2      10    2.0

In [223]:
#Quedamos con la columnas necesarias
pelicula = pelicula[
    [
        "show_id",
        "title",
        "duration_value",
        "duration_unit",
        "release_year",
        "tipo_id",
        "cla_id",
        "fe_id"
    ]
]

In [224]:
#Llave primaria
pelicula.insert(0,"peli_id",range(1,len(pelicula)+1))

In [225]:
#GUARDO CSV
pelicula.to_csv(os.path.join(CARPETA_SALIDA,"pelicula.csv"),index=False,
   encoding="utf-8-sig"
)

CREO TABLA PUENTES

In [226]:
def crear_tabla_puente(
        df,
        pelicula,
        catalogo,
        columna_csv,
        columna_catalogo,
        id_catalogo,
        id_puente):

    relaciones = []

    for _, fila in df.iterrows():

        # Buscar la película
        peli_id = pelicula.loc[pelicula["show_id"] == fila["show_id"],"peli_id"].values[0]

        # Si el dato está vacío lo ignoramos
        if pd.isna(fila[columna_csv]):
            continue

        # Separar por comas
        for valor in str(fila[columna_csv]).split(","):
            valor = valor.strip()

            if valor == "":
                continue

            # Buscar el ID correspondiente
            catalogo_id = catalogo.loc[catalogo[columna_catalogo] == valor,id_catalogo].values[0]

            relaciones.append({id_catalogo: catalogo_id,"peli_id": peli_id})

    puente = pd.DataFrame(relaciones)

    puente.insert(0,id_puente,range(1, len(puente)+1))

    return puente

TABLA PEL_ACT

In [227]:
pel_act = crear_tabla_puente(
    df=df,
    pelicula=pelicula,
    catalogo=actor,
    columna_csv="cast",
    columna_catalogo="nom_cast",
    id_catalogo="actor_id",
    id_puente="pelact_id"
)

#GUARDAR CSV
pel_act.to_csv(os.path.join(CARPETA_SALIDA, "pel_act.csv"),index=False,
    encoding="utf-8-sig"
)

TABLA PEL_DIR

In [228]:
pel_dir = crear_tabla_puente(
    df=df,
    pelicula=pelicula,
    catalogo=director,
    columna_csv="director",
    columna_catalogo="director",
    id_catalogo="direc_id",
    id_puente="peldir_id"
)

#GUARDAR CSV
pel_dir.to_csv(os.path.join(CARPETA_SALIDA, "pel_dir.csv"),index=False,
    encoding="utf-8-sig"
)

TABLA PEL_GEN

In [229]:
pel_gen = crear_tabla_puente(
    df=df,
    pelicula=pelicula,
    catalogo=genero,
    columna_csv="listed_in",
    columna_catalogo="listed_in",
    id_catalogo="gen_id",
    id_puente="pelgen_id"
)

#GUARDAR CSV
pel_gen.to_csv(os.path.join(CARPETA_SALIDA, "pel_gen.csv"),index=False,
    encoding="utf-8-sig")

TABLA PEL_PAS

In [230]:
pel_pas = crear_tabla_puente(
    df=df,
    pelicula=pelicula,
    catalogo=pais,
    columna_csv="country",
    columna_catalogo="country",
    id_catalogo="pais_id",
    id_puente="pelpas_id"
)

#GUARDAR CSV
pel_pas.to_csv(os.path.join(CARPETA_SALIDA, "pel_pas.csv"),index=False,
    encoding="utf-8-sig")